### ISSUE TITLE
installation fails with Python3

### ISSUE THREAD

**Issue by videlec** [jdemeyer/pari_jupyter#2]
Running setup.py (path:/tmp/pip-build-k1vf5zu8/pari-jupyter/setup.py) egg_info for package pari-jupyter
        Running command python setup.py egg_info
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-k1vf5zu8/pari-jupyter/setup.py", line 29, in <module>
            gp.communicate('''ok=1; iferr(install("PARI_get_plot_svg", "v"), E, ok=0); quit(!ok);''')
           File "/usr/lib/python3.6/subprocess.py", line 836, in communicate
             stdout, stderr = self._communicate(input, endtime, timeout)
          File "/usr/lib/python3.6/subprocess.py", line 1478, in _communicate
            input_view = memoryview(self._input)
         TypeError: memoryview: a bytes-like object is required, not 'str'
    Cleaning up...
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k1vf5zu8/pari-jupyter/

**Comment by jdemeyer** [comment]
Fixed in 5f555291e73141f2d7e63f57b7465b6f44dff4ec
