### ISSUE TITLE
kernel installs on Python3 but does not work

### ISSUE THREAD

**Issue by videlec** [jdemeyer/pari_jupyter#6]
Installing with Python3 went fine (see #2) but after launching a worksheet
```
[I 19:11:32.525 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
WARNING:root:kernel 4058dd5e-87a7-455b-9058-e11115b469bc restarted
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vincent/.local/lib/python3.6/site-packages/PARIKernel/__main__.py", line 1, in <module>
    from .kernel import PARIKernel
  File "PARIKernel/io.pxd", line 3, in init PARIKernel.kernel
ImportError: /home/vincent/.local/lib/python3.6/site-packages/PARIKernel/io.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyString_FromStringAndSize
```

**Comment by jdemeyer** [comment]
Fixed in master
