### ISSUE TITLE
python3 json trouble

### ISSUE THREAD

**Issue by videlec** [jdemeyer/pari_jupyter#8]
On Python3, the kernel launches but does not communicate correctly
```
[D 10:29:52.710 NotebookApp] 200 GET /static/base/images/favicon-notebook.ico (::1) 2.39ms
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "PARIKernel/kernel.pyx", line 154, in PARIKernel.kernel.PARIKernel.do_execute
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 351, in send_response
    ident, buffers, track, header, metadata)
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/jupyter_client/session.py", line 737, in send
    to_send = self.serialize(msg, ident)
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/jupyter_client/session.py", line 625, in serialize
    content = self.pack(content)
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/vincent/programming/jup3/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 93, in date_default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: b'x + 1' is not JSON serializable
```

**Comment by jdemeyer** [comment]
I know, working on this...
